modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/bageldotjpg/Bambootiful/issues" #optional

[[mods]] #mandatory
modId="bambootiful" #mandatory
version="1.1.1" #mandatory
displayName="Bambootiful" #mandatory
displayURL="https://discord.gg/zVBFsXp" #optional
logoFile="bambootiful" #optional
credits="TheVillagerKing - textures" #optional
authors="bageldotjpg" #optional

description='''
Bambootiful expands on Bamboo.
It will introduce new blocks, mobs, and weapons themed around Bamboo!
'''

[[dependencies.bambootiful]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"