modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/bageldotjpg/Bambootiful/issues"

[[mods]]
modId="bambootiful"
version="${file.jarVersion}"
displayName="Bambootiful"
# updateJSONURL="http://myurl.me/"
displayURL="https://discord.gg/zVBFsXp"
logoFile="bambootiful"
authors="bageldotjpg"
credits="TheVillagerKing - textures"
description='''
Bambootiful expands on Bamboo.
It will introduce new blocks, mobs, and weapons themed around Bamboo!
'''

[[dependencies.bambootiful]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
